name: epitech_flutter_filestore
description: Epitech project in Flutter
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^0.2.1
  shared_preferences: 0.5.12+4
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+15
  permission_handler: ^5.0.1+1
  flutter_plugin_android_lifecycle: ^1.0.11
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: BluuSuuperstar
      fonts:
        - asset: fonts/BluuSuuperstar-Black.ttf
        - asset: fonts/BluuSuuperstar-BlackItalic.ttf
        - asset: fonts/BluuSuuperstar-Bold.ttf
        - asset: fonts/BluuSuuperstar-BoldItalic.ttf
        - asset: fonts/BluuSuuperstar-Medium.ttf
        - asset: fonts/BluuSuuperstar-MediumItalic.ttf
        - asset: fonts/BluuSuuperstar-MediumItalic.ttf

    - family: SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay-Regular.ttf
